//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECZANE
{
    using System;
    using System.Collections.Generic;
    
    public partial class İlac_cesit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public İlac_cesit()
        {
            this.Fatdetay = new HashSet<Fatdetay>();
            this.Fatura = new HashSet<Fatura>();
            this.Stoktaki_ilaclar = new HashSet<Stoktaki_ilaclar>();
            this.Tedarikciler = new HashSet<Tedarikciler>();
        }
    
        public int İlac_ID { get; set; }
        public string İlac_adı { get; set; }
        public string İlac_turu { get; set; }
        public Nullable<decimal> İlac_fiyat { get; set; }
        public Nullable<double> Total_ilacs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fatdetay> Fatdetay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fatura> Fatura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stoktaki_ilaclar> Stoktaki_ilaclar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tedarikciler> Tedarikciler { get; set; }
    }
}
