//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECZANE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stoktaki_ilaclar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stoktaki_ilaclar()
        {
            this.Fatdetay = new HashSet<Fatdetay>();
        }
    
        public int Stok_ilac_ID { get; set; }
        public string Stok_ilac_ad { get; set; }
        public Nullable<int> Stok_ilac_adet { get; set; }
        public Nullable<int> İlac_ID { get; set; }
        public Nullable<double> Birimfiyatı { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fatdetay> Fatdetay { get; set; }
        public virtual İlac_cesit İlac_cesit { get; set; }
    }
}
