//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECZANE
{
    using System;
    using System.Collections.Generic;
    
    public partial class vFatura
    {
        public string Hasta_tc { get; set; }
        public string Hasta_Adı { get; set; }
        public string Hasta_Soyadı { get; set; }
        public string Hasta_İlaç { get; set; }
        public string Hasta_yas { get; set; }
        public Nullable<int> Hasta_ID { get; set; }
        public Nullable<int> İlac_ID { get; set; }
        public Nullable<int> P_no { get; set; }
        public Nullable<System.DateTime> Fattarıh { get; set; }
        public string İlac_adı { get; set; }
    }
}
